#!/usr/bin/env bash
# Generates docs/js/firebase-config.js from the iOS GoogleService-Info.plist
# (same Firebase project as the Oplix app).

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PLIST="$ROOT/Oplix/GoogleService-Info.plist"
OUT="$ROOT/docs/js/firebase-config.js"
WEB_ID_FILE="$ROOT/docs/firebase-web-app-id.txt"

if [[ ! -f "$PLIST" ]]; then
  echo "Missing $PLIST"
  exit 1
fi

API_KEY=$(plutil -extract API_KEY raw -o - "$PLIST")
PROJECT_ID=$(plutil -extract PROJECT_ID raw -o - "$PLIST")
GCM_SENDER_ID=$(plutil -extract GCM_SENDER_ID raw -o - "$PLIST")
STORAGE_BUCKET=$(plutil -extract STORAGE_BUCKET raw -o - "$PLIST")
IOS_APP_ID=$(plutil -extract GOOGLE_APP_ID raw -o - "$PLIST")

WEB_APP_ID=""
if [[ -f "$WEB_ID_FILE" ]]; then
  WEB_APP_ID=$(tr -d '[:space:]' < "$WEB_ID_FILE")
fi

if [[ -z "$WEB_APP_ID" ]]; then
  WEB_APP_ID="REPLACE_WITH_WEB_APP_ID"
  echo "Note: Add your Firebase Web app ID to docs/firebase-web-app-id.txt"
  echo "      (Firebase Console → Project settings → Your apps → Web)"
fi

cat > "$OUT" <<EOF
/**
 * AUTO-GENERATED by scripts/sync-firebase-web-config.sh
 * iOS app: $IOS_APP_ID
 * Project: $PROJECT_ID (same as GoogleService-Info.plist)
 */
const OPLIX_FIREBASE_CONFIG = {
    apiKey: "$API_KEY",
    authDomain: "$PROJECT_ID.firebaseapp.com",
    projectId: "$PROJECT_ID",
    storageBucket: "$STORAGE_BUCKET",
    messagingSenderId: "$GCM_SENDER_ID",
    appId: "$WEB_APP_ID"
};
EOF

echo "Wrote $OUT"
